from .employees.employee_list import employee_list
from .employees.employee_form import employee_form
from .trainings.training_list import training_list
from .trainings.training_form import training_form
from .home import home
from .auth.logout import logout_user
from .departments.department_list import department_list
from .departments.department_form import department_form
from .computers.computer_list import computer_list
from .computers.computer_form import computer_form
from .computers.computer_details import computer_details
from .employees.employee_details import employee_details